//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduBrain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicantFamilyMember
    {
        public int ApplicantFamilyMemberId { get; set; }
        public string MemberType { get; set; }
        public Nullable<int> ApplicantPersonId { get; set; }
        public Nullable<int> ApplicantStudentId { get; set; }
        public Nullable<int> FamilyId { get; set; }
    }
}
