//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduBrain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicantParent
    {
        public int ApplicantParentId { get; set; }
        public int PersonId { get; set; }
    }
}
