//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduBrain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicantPerson
    {
        public int ApplicantPersonId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<byte> Gender { get; set; }
        public Nullable<System.DateTime> DateApplied { get; set; }
        public Nullable<int> FamilyId { get; set; }
        public string EmailAddress { get; set; }
        public string Title { get; set; }
        public string Job { get; set; }
    }
}
