//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduBrain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicantFamily
    {
        public int FamilyId { get; set; }
        public Nullable<int> ApplicantFatherId { get; set; }
        public Nullable<int> ApplicantMotherId { get; set; }
        public Nullable<int> ApplicantGuardianId { get; set; }
    }
}
