//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduBrain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Locker
    {
        public int LockerId { get; set; }
        public string LockerNumber { get; set; }
        public Nullable<int> StudentId { get; set; }
        public System.DateTime DateAssigned { get; set; }
        public string Location { get; set; }
        public string CombinationNumber { get; set; }
    
        public virtual Locker Locker1 { get; set; }
        public virtual Locker Locker2 { get; set; }
        public virtual Student Student { get; set; }
    }
}
